<img src='logo/dsl-logo.png' width="500" align="center" />

# HR Competition

## Decision Tree

In [59]:
# Bibliotheken einbinden
import numpy as np
import scipy.stats as stats
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

from sklearn.linear_model import LogisticRegression

In [60]:
# Definition einer Klasse für Text Styles
class color:
   PURPLE = '\033[95m'
   CYAN = '\033[96m'
   DARKCYAN = '\033[36m'
   BLUE = '\033[94m'
   GREEN = '\033[92m'
   YELLOW = '\033[93m'
   RED = '\033[91m'
   BOLD = '\033[1m'
   UNDERLINE = '\033[4m'
   END = '\033[0m'

In [61]:
#Laden der Trainings- und Testdaten
X = np.load(file='exchange/hr_06_X.npy')
X_train = np.load(file='exchange/hr_06_X_train.npy')
X_train_scaled = np.load(file='exchange/hr_06_X_train_scaled.npy')
X_test = np.load(file='exchange/hr_06_X_test.npy')
X_test_scaled = np.load(file='exchange/hr_06_X_test_scaled.npy')
y = np.load(file='exchange/hr_06_y.npy')
y_train = np.load(file='exchange/hr_06_y_train.npy')
y_test = np.load(file='exchange/hr_06_y_test.npy')
#df = np.load(file='exchange/hr_06_premodel.npy')

In [62]:
#Decision Tree initialisieren
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train_scaled, y_train)

In [63]:
clf.score(X_test_scaled, y_test)

0.97750000000000004

In [64]:
clf_predictions = clf.predict(X_test_scaled)

In [65]:
print(confusion_matrix(y_test, clf_predictions))

[[1812   35]
 [  19  534]]


In [28]:
print(classification_report(y_test, clf_predictions))

             precision    recall  f1-score   support

          0       0.99      0.98      0.99      1847
          1       0.94      0.97      0.95       553

avg / total       0.98      0.98      0.98      2400



In [29]:
clf_reg = tree.DecisionTreeRegressor()
clf_reg = clf.fit(X_train_scaled, y_train)

In [30]:
clf_reg.score(X_test_scaled, y_test)

0.97791666666666666

In [31]:
clf_reg_predictions = clf.predict(X_test_scaled)
print(confusion_matrix(y_test, clf_reg_predictions))

[[1813   34]
 [  19  534]]


In [32]:
print(classification_report(y_test, clf_predictions))

             precision    recall  f1-score   support

          0       0.99      0.98      0.99      1847
          1       0.94      0.97      0.95       553

avg / total       0.98      0.98      0.98      2400



#### Graphische Darstellung des Entscheidungsbaums

In [33]:
# Install graphviz on MacOS: http://macappstore.org/graphviz/
!pip install graphviz
import graphviz

In [34]:
dot_data = tree.export_graphviz(clf, out_file='temp/tree.dot')


In [35]:
graph = graphviz.Source('temp/tree.dot')


In [36]:
! pip install pydotplus

In [37]:
from sklearn.externals.six import StringIO  
import pydotplus
from IPython.display import Image


In [38]:
dotfile = StringIO() 
tree.export_graphviz(clf, out_file=dotfile) 
pydotplus.graph_from_dot_data(dotfile.getvalue()).write_png("temp/my_tree.png");
print("Decision Tree Graph:")

Decision Tree Graph:


<img src='temp/my_tree.png' width="100%" align="center" />

#### w/o department

In [66]:
#Laden der Trainings- und Testdaten
X = np.load(file='exchange/hr_06_X_wodept.npy')
X_train = np.load(file='exchange/hr_06_X_wodept_train.npy')
X_train_scaled = np.load(file='exchange/hr_06_X_wodept_train_scaled.npy')
X_test = np.load(file='exchange/hr_06_X_wodept_test.npy')
X_test_scaled = np.load(file='exchange/hr_06_X_wodept_test_scaled.npy')
y = np.load(file='exchange/hr_06_y_wodept.npy')
y_train = np.load(file='exchange/hr_06_y_wodept_train.npy')
y_test = np.load(file='exchange/hr_06_y_wodept_test.npy')
#df = np.load(file='exchange/hr_06_premodel.npy')

In [67]:
#Decision Tree initialisieren
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train_scaled, y_train)

In [68]:
clf.score(X_test_scaled, y_test)

0.98166666666666669

In [69]:
clf_predictions = clf.predict(X_test_scaled)

In [70]:
cm = confusion_matrix(y_test, clf_predictions)
print(cm)

[[1822   25]
 [  19  534]]


In [71]:
cm_dict = np.load("exchange/hr_20_cm_dict.npy")
print(cm_dict.item())

{'neural_net': {'cm': array([[1830,   17],
       [  55,  498]]), 'label': 'Neural Network'}, 'random_forest': {'cm': array([[1840,    7],
       [  24,  529]]), 'label': 'Random Forest'}, 'logistic_regression': {'cm': array([[1736,  111],
       [ 345,  208]]), 'label': 'Logistic Regression'}}


In [72]:
cm_dict.item().update({'decision_tree':{'cm': cm, 'label': 'Decision Tree' }})
print(cm_dict)
np.save("exchange/hr_20_cm_dict.npy", cm_dict)

{'neural_net': {'cm': array([[1830,   17],
       [  55,  498]]), 'label': 'Neural Network'}, 'random_forest': {'cm': array([[1840,    7],
       [  24,  529]]), 'label': 'Random Forest'}, 'logistic_regression': {'cm': array([[1736,  111],
       [ 345,  208]]), 'label': 'Logistic Regression'}, 'decision_tree': {'cm': array([[1822,   25],
       [  19,  534]]), 'label': 'Decision Tree'}}


In [73]:
print(classification_report(y_test, clf_predictions))

             precision    recall  f1-score   support

          0       0.99      0.99      0.99      1847
          1       0.96      0.97      0.96       553

avg / total       0.98      0.98      0.98      2400



In [46]:
clf_reg = tree.DecisionTreeRegressor()
clf_reg = clf.fit(X_train_scaled, y_train)

In [47]:
clf_reg.score(X_test_scaled, y_test)

0.98041666666666671

In [48]:
clf_reg_predictions = clf.predict(X_test_scaled)
print(confusion_matrix(y_test, clf_reg_predictions))

[[1819   28]
 [  19  534]]


In [49]:
print(classification_report(y_test, clf_predictions))

             precision    recall  f1-score   support

          0       0.99      0.99      0.99      1847
          1       0.95      0.97      0.96       553

avg / total       0.98      0.98      0.98      2400



#### Graphische Darstellung des Entscheidungsbaums

In [50]:
# Install graphviz on MacOS: http://macappstore.org/graphviz/
!pip install graphviz
import graphviz

In [51]:
dot_data = tree.export_graphviz(clf, out_file='temp/tree.dot')


In [52]:
graph = graphviz.Source('temp/tree.dot')


In [54]:
! pip install pydotplus

In [55]:
from sklearn.externals.six import StringIO  
import pydotplus
from IPython.display import Image


In [56]:
dotfile = StringIO() 
tree.export_graphviz(clf, out_file=dotfile) 
pydotplus.graph_from_dot_data(dotfile.getvalue()).write_png("temp/my_tree_wodept.png");
print("Decision Tree Graph:")

Decision Tree Graph:


<img src='temp/my_tree_wodept.png' width="100%" align="center" />