<img src='logo/dsl-logo.png' width="500" align="center" />

# HR Competition

## Decision Tree

In [1]:
# Bibliotheken einbinden
import numpy as np
import scipy.stats as stats
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

from sklearn.linear_model import LogisticRegression

In [2]:
# Definition einer Klasse für Text Styles
class color:
   PURPLE = '\033[95m'
   CYAN = '\033[96m'
   DARKCYAN = '\033[36m'
   BLUE = '\033[94m'
   GREEN = '\033[92m'
   YELLOW = '\033[93m'
   RED = '\033[91m'
   BOLD = '\033[1m'
   UNDERLINE = '\033[4m'
   END = '\033[0m'

In [3]:
#Laden der Trainings- und Testdaten
X = np.load(file='exchange/hr_06_X.npy')
X_train = np.load(file='exchange/hr_06_X_train.npy')
X_train_scaled = np.load(file='exchange/hr_06_X_train_scaled.npy')
X_test = np.load(file='exchange/hr_06_X_test.npy')
X_test_scaled = np.load(file='exchange/hr_06_X_test_scaled.npy')
y = np.load(file='exchange/hr_06_y.npy')
y_train = np.load(file='exchange/hr_06_y_train.npy')
y_test = np.load(file='exchange/hr_06_y_test.npy')
#df = np.load(file='exchange/hr_06_premodel.npy')

In [4]:
#Decision Tree initialisieren
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train_scaled, y_train)

In [5]:
clf.score(X_test_scaled, y_test)

0.97875000000000001

In [6]:
clf_predictions = clf.predict(X_test_scaled)


In [7]:
print(confusion_matrix(y_test, clf_predictions))

[[1812   35]
 [  16  537]]


In [8]:
print(classification_report(y_test, clf_predictions))

             precision    recall  f1-score   support

          0       0.99      0.98      0.99      1847
          1       0.94      0.97      0.95       553

avg / total       0.98      0.98      0.98      2400



In [9]:
clf_reg = tree.DecisionTreeRegressor()
clf_reg = clf.fit(X_train_scaled, y_train)

In [10]:
clf_reg.score(X_test_scaled, y_test)

0.97999999999999998

In [11]:
clf_reg_predictions = clf.predict(X_test_scaled)
print(confusion_matrix(y_test, clf_reg_predictions))

[[1817   30]
 [  18  535]]


In [12]:
print(classification_report(y_test, clf_predictions))

             precision    recall  f1-score   support

          0       0.99      0.98      0.99      1847
          1       0.94      0.97      0.95       553

avg / total       0.98      0.98      0.98      2400



#### Graphische Darstellung des Entscheidungsbaums

In [13]:
!pip install graphviz
import graphviz

In [14]:
dot_data = tree.export_graphviz(clf, out_file='tree.dot')


In [15]:
graph = graphviz.Source('tree.dot')


In [16]:
! pip install pydotplus

In [17]:
from sklearn.externals.six import StringIO  
import pydotplus 


In [18]:
#dotfile = StringIO() 
#tree.export_graphviz(clf, out_file=dotfile) 
#pydotplus.graph_from_dot_data(dotfile.getvalue()).write_png("my_tree.png")

## Logistic Regression

In [19]:
#Logistische Regression initialisieren
logistic = LogisticRegression()
logistic.fit(X_train_scaled, y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [20]:
logistic.score(X_test_scaled, y_test)

0.81000000000000005

In [21]:
log_predictions = logistic.predict(X_test_scaled)
print(confusion_matrix(y_test, log_predictions))

[[1736  111]
 [ 345  208]]


In [22]:
print(classification_report(y_test, log_predictions))

             precision    recall  f1-score   support

          0       0.83      0.94      0.88      1847
          1       0.65      0.38      0.48       553

avg / total       0.79      0.81      0.79      2400



In [23]:
logistic.predict_proba(X_test_scaled)

array([[ 0.96535847,  0.03464153],
       [ 0.76124429,  0.23875571],
       [ 0.67413157,  0.32586843],
       ..., 
       [ 0.98307882,  0.01692118],
       [ 0.8189979 ,  0.1810021 ],
       [ 0.81303976,  0.18696024]])

In [24]:
np.info(X_train_scaled)

class:  ndarray
shape:  (9599, 22)
strides:  (176, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0xc070040
byteorder:  little
byteswap:  False
type: float64
